export { default as IcFriends } from './ic-friends'
export { default as IcMine } from './ic-mine'
export { default as IcEarn } from './ic-earn'
export { default as IcCheck } from './ic-check'
export { default as IcPlusMembers } from './ic-plus-members'